/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;

import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIDefaults;
import javax.swing.table.DefaultTableCellRenderer;

import logic.HandlingOperationsFileName;
import logic.HeaderRenderer;
import logic.OptimizeTables;
import logic.SpecialCharacterDispatcher;
import logic.StartingAndEndingCreditsHandeler;
import menubar.CreditsMenu_StartingCredits;
import menubar.EditMenu_MoveDownListener;
import menubar.EditMenu_MoveUpListener;
import menubar.EditMenu_RemoveRowListener;
import menubar.FileMenu_OpenMenuItemListener;
import menubar.FileMenu_StartingNewOperationsListener;
import operationspanel.Operation;
import operationspanel.Operations_AddOperationsButtonListener;
import operationspanel.Operations_TableKeyListener;
import operationspanel.Operations_TableModel;
import operationspanel.Operations_TableMouseListener;
import operationspanel.Operations_TextFieldKeyListener;
import savecontactspanel.SaveContactsPanel_AddContactButtonListener;
import savecontactspanel.SaveContactsPanel_TableKeyListener;
import savecontactspanel.SaveContactsPanel_TableModel;
import savecontactspanel.SaveContactsPanel_TableMouseListener;
import savecontactspanel.SaveContacts_TextFiledsKeyListener;
import toolbar.ToolBar_DuesValuesJTextFieldHandling;
import toolbar.ToolBar_OperationsValueTextFieldHandling;
import duespanel.DuesPanel_AddContactButtonListener;
import duespanel.DuesPanel_TableKeyListener;
import duespanel.DuesPanel_TableModel;
import duespanel.DuesPanel_TableMouseListener;
import duespanel.DuesPanel_TextFiledsKeyListener;

/**
 *
 * @author Khaled
 */
@SuppressWarnings("serial")
public class MainFrame extends javax.swing.JFrame {

    private JMenuItem aboutMenu_developer;
    private SpecialCharacterDispatcher specialCharacterDispatcher;
	/**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	handlingOperationsFileName = new HandlingOperationsFileName(this);
    	optimizeTables = new OptimizeTables();
        toolBar = new javax.swing.JToolBar();
        toolBar_BeginningWithLabel = new javax.swing.JLabel();
        toolBar_BeginningWithLabelTextField = new javax.swing.JTextField();
        toolBar_Separator1 = new javax.swing.JToolBar.Separator();
        toolBar_CreditsTransferedLabel = new javax.swing.JLabel();
        toolBar_CreditsTransferedLabelTextField = new javax.swing.JTextField();
        toolBar_Separator2 = new javax.swing.JToolBar.Separator();
        toolBar_CreditsYouHaveLabel = new javax.swing.JLabel();
        toolBar_CreditsYouHaveLabelTextField = new javax.swing.JTextField();
        toolBar_Separator3 = new javax.swing.JToolBar.Separator();
        toolBar_DuesValuesLabel = new javax.swing.JLabel();
        toolBar_DuesValuesTextField = new javax.swing.JTextField();
        tabbedPane = new javax.swing.JTabbedPane();
        operationsPanel = new javax.swing.JPanel();
        operationsPanel_ScrollPane = new javax.swing.JScrollPane();
        operationsPanel_Table = new javax.swing.JTable();
        operations_TableModel = new Operations_TableModel(handlingOperationsFileName.controller, handlingOperationsFileName);
        operationsPanel_AddOperationButton = new javax.swing.JButton();
        operationsPanel_OperationLabel = new javax.swing.JLabel();
        operationsPanel_OperationTextField = new javax.swing.JTextField();
        operationsPanel_ValueLabel = new javax.swing.JLabel();
        operationsPanel_ValueTextField = new javax.swing.JTextField();
        operationsPanel_AccomplisedCheckBox = new javax.swing.JCheckBox();
        duesPanel = new javax.swing.JPanel();
        duesPanel_ScrollPane = new javax.swing.JScrollPane();
        duesPanel_Table = new javax.swing.JTable();
        duesPanel_TableModel = new DuesPanel_TableModel();
        duesPanel_AddContactButton = new javax.swing.JButton();
        duesPanel_PersonNameLabel = new javax.swing.JLabel();
        duesPanel_PersonNameTextField = new javax.swing.JTextField();
        duesPanel_ValueLabel = new javax.swing.JLabel();
        duesPanel_ValueTextField = new javax.swing.JTextField();
        duesPanel_RelatedToLabel = new javax.swing.JLabel();
        duesPanel_RelatedToTextField = new javax.swing.JTextField();
        saveContactsPanel = new javax.swing.JPanel();
        saveContactsPanel_ScrollPane = new javax.swing.JScrollPane();
        saveContactsPanel_Table = new javax.swing.JTable();
        saveContactsPanel_TableModel = new SaveContactsPanel_TableModel();
        saveContactsPanel_AddContactButton = new javax.swing.JButton();
        saveContactsPanel_PersonNameLabel = new javax.swing.JLabel();
        saveContactsPanel_PersonNameTextField = new javax.swing.JTextField();
        saveContactsPanel_PersonNumberLabel = new javax.swing.JLabel();
        saveContactsPanel_PersonNumberTextField = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileMenu_StartingNewOperationsMenuItem = new javax.swing.JMenuItem();
        fileMenu_OpenMenuItem = new javax.swing.JMenuItem();
        fileMenu_Separator = new javax.swing.JPopupMenu.Separator();
        fileMenu_ExitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        editMenu_MoveUp = new javax.swing.JMenuItem();
        editMenu_MoveDown = new javax.swing.JMenuItem();
        editMenu_RemoveRow = new javax.swing.JMenuItem();
        creditsMenu = new javax.swing.JMenu();
        aboutMenu = new javax.swing.JMenu();
        creditsMenu_StartingCreditsMenuItem = new javax.swing.JMenuItem();
        aboutMenu_Shortcuts = new javax.swing.JMenuItem();
        aboutMenu_developer = new javax.swing.JMenuItem();
        specialCharacterDispatcher = new SpecialCharacterDispatcher(tabbedPane, operationsPanel, operationsPanel_OperationTextField, operationsPanel_Table, operationsPanel_AccomplisedCheckBox);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );

        startingAndEndingCreditsHandeler = new StartingAndEndingCreditsHandeler(toolBar_BeginningWithLabelTextField, toolBar_CreditsTransferedLabelTextField, toolBar_CreditsYouHaveLabelTextField, operations_TableModel);
        
        toolBar_DuesValuesJTextFieldHandling = new ToolBar_DuesValuesJTextFieldHandling(toolBar_DuesValuesTextField, duesPanel_TableModel);
        toolBar_OperationsValueTextFieldHandling = new ToolBar_OperationsValueTextFieldHandling(toolBar_CreditsTransferedLabelTextField, operations_TableModel, startingAndEndingCreditsHandeler);
        
        handlingOperationsFileName.setOperations_TableModel(operations_TableModel);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SkyTech Fawry");
        setName("Sky Fawry"); // NOI18N
        setPreferredSize(new Dimension(1200, 700));
        
        toolBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        toolBar.setFloatable(false);
        toolBar.setRollover(true);

        toolBar_BeginningWithLabel.setFont(new Font("SansSerif", Font.BOLD, 15));
        toolBar_BeginningWithLabel.setText("  : »œ«Ì… «·—’Ìœ  ");
        toolBar.add(toolBar_BeginningWithLabel);

        toolBar_BeginningWithLabelTextField.setEditable(false);
        toolBar_BeginningWithLabelTextField.setMinimumSize(new java.awt.Dimension(100, 40));
        toolBar_BeginningWithLabelTextField.setPreferredSize(new java.awt.Dimension(100, 40));
        toolBar_BeginningWithLabelTextField.setFont(new Font(Font.SANS_SERIF, Font.CENTER_BASELINE, 16));
        toolBar_BeginningWithLabelTextField.setHorizontalAlignment(JTextField.CENTER);
        toolBar.add(toolBar_BeginningWithLabelTextField);

        toolBar_Separator1.setMaximumSize(new java.awt.Dimension(20, 32767));
        toolBar_Separator1.setMinimumSize(new java.awt.Dimension(20, 0));
        toolBar_Separator1.setName(""); // NOI18N
        toolBar.add(toolBar_Separator1);

        toolBar_CreditsTransferedLabel.setFont(new Font("SansSerif", Font.BOLD, 15));
        toolBar_CreditsTransferedLabel.setText("  : «·—’Ìœ «·„ÕÊ·     ");
        toolBar.add(toolBar_CreditsTransferedLabel);

        toolBar_CreditsTransferedLabelTextField.setEditable(false);
        toolBar_CreditsTransferedLabelTextField.setMinimumSize(new java.awt.Dimension(100, 40));
        toolBar_CreditsTransferedLabelTextField.setPreferredSize(new java.awt.Dimension(100, 40));
        toolBar_CreditsTransferedLabelTextField.setFont(new Font(Font.SANS_SERIF, Font.CENTER_BASELINE, 16));
        toolBar_CreditsTransferedLabelTextField.setHorizontalAlignment(JTextField.CENTER);
        toolBar.add(toolBar_CreditsTransferedLabelTextField);

        toolBar_Separator2.setMaximumSize(new java.awt.Dimension(20, 32767));
        toolBar_Separator2.setMinimumSize(new java.awt.Dimension(20, 0));
        toolBar.add(toolBar_Separator2);

        toolBar_CreditsYouHaveLabel.setFont(new Font("SansSerif", Font.BOLD, 15));
        toolBar_CreditsYouHaveLabel.setText("  : «·—’Ìœ «·„ »ﬁÌ     ");
        toolBar.add(toolBar_CreditsYouHaveLabel);

        toolBar_CreditsYouHaveLabelTextField.setEditable(false);
        toolBar_CreditsYouHaveLabelTextField.setMinimumSize(new java.awt.Dimension(100, 40));
        toolBar_CreditsYouHaveLabelTextField.setPreferredSize(new java.awt.Dimension(100, 40));
        toolBar_CreditsYouHaveLabelTextField.setFont(new Font(Font.SANS_SERIF, Font.CENTER_BASELINE, 16));
        toolBar_CreditsYouHaveLabelTextField.setHorizontalAlignment(JTextField.CENTER);
        toolBar.add(toolBar_CreditsYouHaveLabelTextField);
        toolBar.add(toolBar_Separator3);

        toolBar_DuesValuesLabel.setFont(new Font("SansSerif", Font.BOLD, 15));
        toolBar_DuesValuesLabel.setText("  : «·«Ê«Ã·     ");
        toolBar.add(toolBar_DuesValuesLabel);

        toolBar_DuesValuesTextField.setEditable(false);
        toolBar_DuesValuesTextField.setMinimumSize(new java.awt.Dimension(100, 60));
        toolBar_DuesValuesTextField.setPreferredSize(new java.awt.Dimension(100, 60));
        toolBar_DuesValuesTextField.setFont(new Font(Font.SANS_SERIF, Font.CENTER_BASELINE, 16));
        toolBar_DuesValuesTextField.setHorizontalAlignment(JTextField.CENTER);
        toolBar.add(toolBar_DuesValuesTextField);

        tabbedPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SkyTech", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new Font("SansSerif", Font.BOLD, 14)));


        operationsPanel_Table.setModel(operations_TableModel);
        
        operationsPanel_ScrollPane.setViewportView(operationsPanel_Table);
        if (operationsPanel_Table.getColumnModel().getColumnCount() > 0) {
            operationsPanel_Table.getColumnModel().getColumn(0).setPreferredWidth(85);
            operationsPanel_Table.getColumnModel().getColumn(0).setMaxWidth(125);
            operationsPanel_Table.getColumnModel().getColumn(1).setPreferredWidth(230);
            operationsPanel_Table.getColumnModel().getColumn(1).setMaxWidth(270);
            operationsPanel_Table.getColumnModel().getColumn(2).setPreferredWidth(85);
            operationsPanel_Table.getColumnModel().getColumn(2).setMaxWidth(125);
            operationsPanel_Table.getColumnModel().getColumn(3).setPreferredWidth(85);
            operationsPanel_Table.getColumnModel().getColumn(3).setMaxWidth(120);
            operationsPanel_Table.getColumnModel().getColumn(4).setPreferredWidth(140);
            operationsPanel_Table.getColumnModel().getColumn(4).setMaxWidth(170);
            operationsPanel_Table.getColumnModel().getColumn(5).setPreferredWidth(140);
            operationsPanel_Table.getColumnModel().getColumn(5).setMaxWidth(170);
        }
        
        operationsPanel_AddOperationButton.setText("«÷«›… ⁄„·Ì…");
        operationsPanel_AddOperationButton.setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 15));

        operationsPanel_OperationLabel.setText("«·⁄„·Ì…");
        operationsPanel_OperationLabel.setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 15));
//        operationsPanel_OperationLabel.setDisplayedMnemonic(KeyEvent.VK_O);
//        operationsPanel_OperationLabel.setLabelFor(operationsPanel_OperationTextField);

        operationsPanel_OperationTextField.setMinimumSize(new java.awt.Dimension(100, 28));
        operationsPanel_OperationTextField.setPreferredSize(new java.awt.Dimension(100, 28));
        operationsPanel_OperationTextField.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 15));
        operationsPanel_OperationTextField.setHorizontalAlignment(JLabel.CENTER);

        operationsPanel_ValueLabel.setText("«·ﬁÌ„…");
        operationsPanel_ValueLabel.setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 15));
//        operationsPanel_ValueLabel.setDisplayedMnemonic(KeyEvent.VK_V);
//        operationsPanel_ValueLabel.setLabelFor(operationsPanel_ValueTextField);

        operationsPanel_ValueTextField.setMinimumSize(new java.awt.Dimension(100, 28));
        operationsPanel_ValueTextField.setPreferredSize(new java.awt.Dimension(100, 28));
        operationsPanel_ValueTextField.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 15));
        operationsPanel_ValueTextField.setHorizontalAlignment(JLabel.CENTER);

        operationsPanel_AccomplisedCheckBox.setText("⁄„·Ì… ‰«ÃÕ…");
        operationsPanel_AccomplisedCheckBox.setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 15));
//        operationsPanel_AccomplisedCheckBox.setDisplayedMnemonicIndex(0);
//        operationsPanel_AccomplisedCheckBox.setMnemonic(KeyEvent.VK_A);
        
        javax.swing.GroupLayout operationsPanelLayout = new javax.swing.GroupLayout(operationsPanel);
        operationsPanel.setLayout(operationsPanelLayout);
        operationsPanelLayout.setHorizontalGroup(
            operationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(operationsPanel_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
            .addGroup(operationsPanelLayout.createSequentialGroup()
                .addComponent(operationsPanel_AddOperationButton)
                .addGap(18, 18, 18)
                .addComponent(operationsPanel_OperationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operationsPanel_OperationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(operationsPanel_ValueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operationsPanel_ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(operationsPanel_AccomplisedCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        operationsPanelLayout.setVerticalGroup(
            operationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, operationsPanelLayout.createSequentialGroup()
                .addGroup(operationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operationsPanel_AddOperationButton)
                    .addComponent(operationsPanel_OperationLabel)
                    .addComponent(operationsPanel_OperationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operationsPanel_ValueLabel)
                    .addComponent(operationsPanel_ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operationsPanel_AccomplisedCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operationsPanel_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
        );

        tabbedPane.addTab("⁄„·Ì«  ›Ê—Ì", operationsPanel);
        
        /////////////////////////////////////////////////////////////////////////////////////////////////////////
        optimizeTables.optimize(operationsPanel_Table);
        handlingOperationsFileName.loadController();
        operations_TableModel.setController(handlingOperationsFileName.controller);
        operations_TableModel.loadFromFile();
        toolBar_OperationsValueTextFieldHandling.loadOperationsValues();
        startingAndEndingCreditsHandeler.setStartingCredits(Operation.getStartingCredits());
        operationsPanel_AddOperationButton.addActionListener(new Operations_AddOperationsButtonListener(operations_TableModel,  operationsPanel_OperationTextField,toolBar_OperationsValueTextFieldHandling,  operationsPanel_ValueTextField, operationsPanel_AccomplisedCheckBox,  operationsPanel_Table));
        operationsPanel_OperationTextField.addKeyListener(new Operations_TextFieldKeyListener( operations_TableModel, operationsPanel_OperationTextField, operationsPanel_ValueTextField, operationsPanel_AccomplisedCheckBox, operationsPanel_Table, toolBar_OperationsValueTextFieldHandling));
        operationsPanel_ValueTextField.addKeyListener(new Operations_TextFieldKeyListener(operations_TableModel, operationsPanel_OperationTextField, operationsPanel_ValueTextField, operationsPanel_AccomplisedCheckBox, operationsPanel_Table, toolBar_OperationsValueTextFieldHandling));
        operationsPanel_AccomplisedCheckBox.addKeyListener(new Operations_TextFieldKeyListener(operations_TableModel, operationsPanel_OperationTextField, operationsPanel_ValueTextField, operationsPanel_AccomplisedCheckBox, operationsPanel_Table, toolBar_OperationsValueTextFieldHandling));
        operationsPanel_Table.addKeyListener(new Operations_TableKeyListener(operationsPanel_Table, operationsPanel_OperationTextField, operations_TableModel, toolBar_OperationsValueTextFieldHandling));
        operations_TableModel.setOperationsPanel_Table(operationsPanel_Table);
        operations_TableModel.setToolBar_OperationsValueTextFieldHandling(toolBar_OperationsValueTextFieldHandling);
        operationsPanel_Table.addMouseListener(new Operations_TableMouseListener(operations_TableModel, operationsPanel_Table));
        for (int i = 0; i < operationsPanel_Table.getColumnCount(); i++) {
			if (i != 3) {
				operationsPanel_Table.getColumnModel().getColumn(i)
						.setCellRenderer(centerRenderer);
			}
		}
        operationsPanel_Table.getTableHeader().setDefaultRenderer(new HeaderRenderer(operationsPanel_Table));
		operationsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "⁄„·Ì«  ›Ê—Ì - ( " + operations_TableModel.getFileName() +" )" , javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new Font("SansSerif", Font.BOLD, 15)));
        /////////////////////////////////////////////////////////////////////////////////////////////////////////

        
        duesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "«·«Ê«Ã·", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new Font("SansSerif", Font.BOLD, 15)));
        
        duesPanel_Table.setModel(duesPanel_TableModel);
        
        duesPanel_ScrollPane.setViewportView(duesPanel_Table);
        if (duesPanel_Table.getColumnModel().getColumnCount() > 0) {
        	duesPanel_Table.getColumnModel().getColumn(0).setPreferredWidth(230);
        	duesPanel_Table.getColumnModel().getColumn(0).setMaxWidth(270);
            duesPanel_Table.getColumnModel().getColumn(1).setPreferredWidth(85);
            duesPanel_Table.getColumnModel().getColumn(1).setMaxWidth(125);
            duesPanel_Table.getColumnModel().getColumn(2).setPreferredWidth(270);
            duesPanel_Table.getColumnModel().getColumn(2).setMaxWidth(270);
            duesPanel_Table.getColumnModel().getColumn(3).setPreferredWidth(230);
            duesPanel_Table.getColumnModel().getColumn(3).setMaxWidth(270);
        }

        duesPanel_AddContactButton.setText("«÷«›… «Ã·");
        duesPanel_AddContactButton.setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 15));

        duesPanel_PersonNameLabel.setText("«·«”„");
        duesPanel_PersonNameLabel.setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 15));

        duesPanel_PersonNameTextField.setMinimumSize(new java.awt.Dimension(100, 28));
        duesPanel_PersonNameTextField.setPreferredSize(new java.awt.Dimension(100, 28));
        duesPanel_PersonNameTextField.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 15));
        duesPanel_PersonNameTextField.setHorizontalAlignment(JLabel.CENTER);

        duesPanel_ValueLabel.setText("«·ﬁÌ„…");
        duesPanel_ValueLabel.setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 15));

        duesPanel_ValueTextField.setMinimumSize(new java.awt.Dimension(100, 28));
        duesPanel_ValueTextField.setPreferredSize(new java.awt.Dimension(100, 28));
        duesPanel_ValueTextField.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 15));
        duesPanel_ValueTextField.setHorizontalAlignment(JLabel.CENTER);

        duesPanel_RelatedToLabel.setText("„·«ÕŸ« ");
        duesPanel_RelatedToLabel.setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 15));

        duesPanel_RelatedToTextField.setMinimumSize(new java.awt.Dimension(100, 28));
        duesPanel_RelatedToTextField.setPreferredSize(new java.awt.Dimension(100, 28));
        duesPanel_RelatedToTextField.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 15));
        duesPanel_RelatedToTextField.setHorizontalAlignment(JLabel.CENTER);

        javax.swing.GroupLayout duesPanelLayout = new javax.swing.GroupLayout(duesPanel);
        duesPanel.setLayout(duesPanelLayout);
        duesPanelLayout.setHorizontalGroup(
            duesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(duesPanel_ScrollPane)
            .addGroup(duesPanelLayout.createSequentialGroup()
                .addComponent(duesPanel_AddContactButton)
                .addGap(18, 18, 18)
                .addComponent(duesPanel_PersonNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duesPanel_PersonNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(duesPanel_ValueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duesPanel_ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(duesPanel_RelatedToLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duesPanel_RelatedToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        duesPanelLayout.setVerticalGroup(
            duesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, duesPanelLayout.createSequentialGroup()
                .addGroup(duesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duesPanel_AddContactButton)
                    .addComponent(duesPanel_PersonNameLabel)
                    .addComponent(duesPanel_PersonNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duesPanel_ValueLabel)
                    .addComponent(duesPanel_ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duesPanel_RelatedToLabel)
                    .addComponent(duesPanel_RelatedToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duesPanel_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
        );

        tabbedPane.addTab("«·«Ê«Ã·", duesPanel);
   
        
        
        
        
        
        //////////////////////////////////////////////////////////////////////////////////
        optimizeTables.optimize(duesPanel_Table);
        duesPanel_TableModel.loadFromFile();
        toolBar_DuesValuesJTextFieldHandling.loadDuesValues();
        duesPanel_AddContactButton.addActionListener(new DuesPanel_AddContactButtonListener(duesPanel_TableModel, duesPanel_PersonNameTextField, duesPanel_ValueTextField, duesPanel_RelatedToTextField, toolBar_DuesValuesJTextFieldHandling, duesPanel_Table));
        duesPanel_PersonNameTextField.addKeyListener(new DuesPanel_TextFiledsKeyListener(duesPanel_TableModel, duesPanel_PersonNameTextField, duesPanel_ValueTextField, duesPanel_RelatedToTextField, toolBar_DuesValuesJTextFieldHandling, duesPanel_Table));
        duesPanel_ValueTextField.addKeyListener(new DuesPanel_TextFiledsKeyListener(duesPanel_TableModel, duesPanel_PersonNameTextField, duesPanel_ValueTextField, duesPanel_RelatedToTextField, toolBar_DuesValuesJTextFieldHandling, duesPanel_Table));
        duesPanel_RelatedToTextField.addKeyListener(new DuesPanel_TextFiledsKeyListener(duesPanel_TableModel, duesPanel_PersonNameTextField, duesPanel_ValueTextField, duesPanel_RelatedToTextField, toolBar_DuesValuesJTextFieldHandling, duesPanel_Table));
        duesPanel_TableModel.setDuesPanel_Table(duesPanel_Table);
        duesPanel_TableModel.setToolBar_DuesValuesJTextFieldHandling(toolBar_DuesValuesJTextFieldHandling);
        duesPanel_Table.addMouseListener(new DuesPanel_TableMouseListener(duesPanel_TableModel, duesPanel_Table));
        duesPanel_Table.addKeyListener(new DuesPanel_TableKeyListener(tabbedPane, operationsPanel_OperationTextField));
        for (int i = 0; i < duesPanel_Table.getColumnCount(); i++) {
        	duesPanel_Table.getColumnModel().getColumn(i)
        	.setCellRenderer(centerRenderer);
		}
        duesPanel_Table.getTableHeader().setDefaultRenderer(new HeaderRenderer(duesPanel_Table));
        ///////////////////////////////////////////////////////////////////////////////////
        
        
        
        
        
        
        saveContactsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "«—ﬁ«„ «·ÂÊ« ›", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new Font("SansSerif", Font.BOLD, 15)));
        
        saveContactsPanel_Table.setModel(saveContactsPanel_TableModel);
        
        saveContactsPanel_ScrollPane.setViewportView(saveContactsPanel_Table);
        if (saveContactsPanel_Table.getColumnModel().getColumnCount() > 0) {
        	saveContactsPanel_Table.getColumnModel().getColumn(0).setPreferredWidth(230);
        	saveContactsPanel_Table.getColumnModel().getColumn(0).setMaxWidth(270);
        	saveContactsPanel_Table.getColumnModel().getColumn(1).setPreferredWidth(230);
        	saveContactsPanel_Table.getColumnModel().getColumn(1).setMaxWidth(270);
        }        
        
        saveContactsPanel_AddContactButton.setText("«÷«›… —ﬁ„");
        saveContactsPanel_AddContactButton.setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 15));
        
        saveContactsPanel_PersonNameLabel.setText("«·«”„");
        saveContactsPanel_PersonNameLabel.setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 15));

        saveContactsPanel_PersonNameTextField.setMinimumSize(new java.awt.Dimension(100, 28));
        saveContactsPanel_PersonNameTextField.setPreferredSize(new java.awt.Dimension(100, 28));
        saveContactsPanel_PersonNameTextField.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 15));
        saveContactsPanel_PersonNameTextField.setHorizontalAlignment(JLabel.CENTER);

        saveContactsPanel_PersonNumberLabel.setText("«·—ﬁ„");
        saveContactsPanel_PersonNumberLabel.setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 15));

        saveContactsPanel_PersonNumberTextField.setMinimumSize(new java.awt.Dimension(100, 28));
        saveContactsPanel_PersonNumberTextField.setPreferredSize(new java.awt.Dimension(100, 28));
        saveContactsPanel_PersonNumberTextField.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 15));
        saveContactsPanel_PersonNumberTextField.setHorizontalAlignment(JLabel.CENTER);

        javax.swing.GroupLayout saveContactsPanelLayout = new javax.swing.GroupLayout(saveContactsPanel);
        saveContactsPanel.setLayout(saveContactsPanelLayout);
        saveContactsPanelLayout.setHorizontalGroup(
            saveContactsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(saveContactsPanel_ScrollPane)
            .addGroup(saveContactsPanelLayout.createSequentialGroup()
                .addComponent(saveContactsPanel_AddContactButton)
                .addGap(18, 18, 18)
                .addComponent(saveContactsPanel_PersonNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveContactsPanel_PersonNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveContactsPanel_PersonNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveContactsPanel_PersonNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 248, Short.MAX_VALUE))
        );
        saveContactsPanelLayout.setVerticalGroup(
            saveContactsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saveContactsPanelLayout.createSequentialGroup()
                .addGroup(saveContactsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveContactsPanel_PersonNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveContactsPanel_PersonNameLabel)
                    .addComponent(saveContactsPanel_PersonNumberLabel)
                    .addComponent(saveContactsPanel_PersonNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveContactsPanel_AddContactButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveContactsPanel_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
        );
        
        
        
        ////////////////////////////////////////////////////////////////////////////////////
        optimizeTables.optimize(saveContactsPanel_Table);
        saveContactsPanel_TableModel.loadFromFile();
        saveContactsPanel_AddContactButton.addActionListener(new SaveContactsPanel_AddContactButtonListener(saveContactsPanel_Table, saveContactsPanel_TableModel, 
        		saveContactsPanel_PersonNameTextField, saveContactsPanel_PersonNumberTextField));
        saveContactsPanel_PersonNameTextField.addKeyListener(new SaveContacts_TextFiledsKeyListener(saveContactsPanel_Table, saveContactsPanel_PersonNameTextField, saveContactsPanel_PersonNumberTextField, saveContactsPanel_TableModel));
        saveContactsPanel_PersonNumberTextField.addKeyListener(new SaveContacts_TextFiledsKeyListener(saveContactsPanel_Table, saveContactsPanel_PersonNameTextField, saveContactsPanel_PersonNumberTextField, saveContactsPanel_TableModel));
        saveContactsPanel_Table.addMouseListener(new SaveContactsPanel_TableMouseListener(saveContactsPanel_Table, saveContactsPanel_TableModel));
        saveContactsPanel_Table.addKeyListener(new SaveContactsPanel_TableKeyListener(saveContactsPanel_Table, tabbedPane, operationsPanel_OperationTextField, saveContactsPanel_TableModel));
        for (int i = 0; i < saveContactsPanel_Table.getColumnCount(); i++) {
        	saveContactsPanel_Table.getColumnModel().getColumn(i)
        	.setCellRenderer(centerRenderer);
		}
        saveContactsPanel_Table.getTableHeader().setDefaultRenderer(new HeaderRenderer(saveContactsPanel_Table));
        //////////////////////////////////////////////////////////////////////////

       
        
        
        tabbedPane.addTab("«—ﬁ«„ «·ÂÊ« ›", saveContactsPanel);
        tabbedPane.setFont(new Font("SansSerif", Font.PLAIN, 15));
        
        fileMenu.setText("File");

        fileMenu_StartingNewOperationsMenuItem.setText("Starting New Operations");
//        fileMenu_StartingNewOperationsMenuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_N, InputEvent.CTRL_DOWN_MASK, false));
        fileMenu.add(fileMenu_StartingNewOperationsMenuItem);
        fileMenu.addSeparator();

        ///////////////////////////////////////////////////////////////////////////////////////
        fileMenu_StartingNewOperationsMenuItem.addActionListener(new FileMenu_StartingNewOperationsListener(toolBar_OperationsValueTextFieldHandling, toolBar_BeginningWithLabelTextField, startingAndEndingCreditsHandeler, handlingOperationsFileName, MainFrame.this, operations_TableModel, operationsPanel));
        ///////////////////////////////////////////////////////////////////////////////////////
        
        
        fileMenu_OpenMenuItem.setText("Open");
//        fileMenu_OpenMenuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_O, InputEvent.CTRL_DOWN_MASK, false));
        fileMenu.add(fileMenu_OpenMenuItem);
        
        ///////////////////////////////////////////////////////////////////////////////////////
        fileMenu_OpenMenuItem.addActionListener(new FileMenu_OpenMenuItemListener(operationsPanel, handlingOperationsFileName, operations_TableModel, toolBar_OperationsValueTextFieldHandling, startingAndEndingCreditsHandeler));
        ///////////////////////////////////////////////////////////////////////////////////////

        fileMenu.add(fileMenu_Separator);

        fileMenu_ExitMenuItem.setText("Exit");
        fileMenu.add(fileMenu_ExitMenuItem);
        
        
        fileMenu_ExitMenuItem.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				dispose();
				System.gc();
			}
		});

        menuBar.add(fileMenu);

        editMenu.setText("Edit");

        editMenu_MoveUp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK, false));
        editMenu_MoveUp.setText("Move Up");
        editMenu.add(editMenu_MoveUp);
        
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////
        editMenu_MoveUp.addActionListener(new EditMenu_MoveUpListener(tabbedPane, saveContactsPanel_Table, saveContactsPanel_TableModel, duesPanel_Table, duesPanel_TableModel, operationsPanel_Table,  operations_TableModel));
        ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        
        editMenu_MoveDown.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        editMenu_MoveDown.setText("Move Down");
        editMenu.add(editMenu_MoveDown);
        
        ///////////////////////////////////////////////////////////////////////////////////////////////////////
        editMenu_MoveDown.addActionListener(new EditMenu_MoveDownListener(tabbedPane, saveContactsPanel_Table, saveContactsPanel_TableModel, duesPanel_Table, duesPanel_TableModel,operationsPanel_Table,  operations_TableModel));
        //////////////////////////////////////////////////////////////////////////////////////////////////////
        
        editMenu_RemoveRow.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        editMenu_RemoveRow.setText("Remove Row");
        editMenu.add(editMenu_RemoveRow);
        menuBar.add(editMenu);
        
        ////////////////////////////////////////////////////////////////////////////////////////////
        editMenu_RemoveRow.addActionListener(new EditMenu_RemoveRowListener(tabbedPane, saveContactsPanel_Table, saveContactsPanel_TableModel, duesPanel_Table, duesPanel_TableModel, toolBar_DuesValuesJTextFieldHandling,operationsPanel_Table, operations_TableModel, toolBar_OperationsValueTextFieldHandling));
        ///////////////////////////////////////////////////////////////////////////////////////
        
        
        
        
        
        
        creditsMenu.setText("Credits");
        creditsMenu_StartingCreditsMenuItem.setText("Starting Credits");
//        creditsMenu_StartingCreditsMenuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, InputEvent.CTRL_DOWN_MASK, false));
        creditsMenu.add(creditsMenu_StartingCreditsMenuItem);
        menuBar.add(creditsMenu);
        
        
        
        
        ////////////////////////////////////////////////////////////////////////////////////////////
        creditsMenu_StartingCreditsMenuItem.addActionListener(new CreditsMenu_StartingCredits(this, startingAndEndingCreditsHandeler));
        /////////////////////////////////////////////////////////////////////////////////////////
        
        
        
        
        aboutMenu.setText("About");
        aboutMenu_Shortcuts.setText("Shortcuts");
        aboutMenu_developer.setText("Developer");
        aboutMenu.add(aboutMenu_Shortcuts);
        aboutMenu.add(aboutMenu_developer);
        menuBar.add(aboutMenu);
        
        
        
        /////////////////////////////////////////////////////////////////////////////////////
        aboutMenu_Shortcuts.addActionListener(new ActionListener() {
        	@Override
        	public void actionPerformed(ActionEvent arg0) {
        		String message = "- In operations and contacts table :\n" 
        				+ "- CTRL + ENTER : to copy operation in table - to keep the operation text in Text Fields. \n" 
        				+ "- ''\\'' : to set operation accomplished. \n"
        				+ "- ALT + DOWN : to select last operation in operations panel \n"
        				+ "- ` to select operations text filed from any panel.";
        		JOptionPane.showMessageDialog(MainFrame.this, message, "Shortcuts", JOptionPane.INFORMATION_MESSAGE);
        	}
        });        
        aboutMenu_developer.addActionListener(new ActionListener() {
        	@Override
        	public void actionPerformed(ActionEvent arg0) {
        		String message = "Developed by : \n" 
        				+ "Khaled Saad Abdullah \n"
        				+ "Email: elgendy1204@yahoo.com";
        		JOptionPane.showMessageDialog(MainFrame.this, message, "Shortcuts", JOptionPane.INFORMATION_MESSAGE);
        	}
        });        
        /////////////////////////////////////////////////////////////////////////////////////
        
        
        
        
        
        setJMenuBar(menuBar);
        
        
        
        
        
        /////////////////////////////////////////////////////////////////////////////////
        addWindowFocusListener(new WindowFocusListener() {
			public void windowLostFocus(WindowEvent arg0) {}
			public void windowGainedFocus(WindowEvent arg0) {
				if (tabbedPane.getSelectedIndex() == 0) {
					operationsPanel_OperationTextField.requestFocusInWindow();
				}
			}
		});
        
//        addWindowListener(new WindowAdapter(){
//        	@Override
//        	public void windowClosing(WindowEvent e) {
//        		dispose();
//        		System.gc();
//        	}
//        });
//        ///////////////////////////////////////////////////////////////////////////
        
        


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane))
        );

        pack();
        setLocationRelativeTo(null);
        KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher(specialCharacterDispatcher);
        System.gc();
    }
    
    public static void main(String args[]) {

    	try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    UIDefaults defaults = javax.swing.UIManager.getLookAndFeelDefaults();
    	            defaults.put("Table.gridColor", new Color (214,217,223));
    	            defaults.put("Table.showGrid", true);
    	            defaults.put("Table.intercellSpacing", new Dimension(1, 1));
    	            defaults.put("TableHeader.font", new Font(Font.SANS_SERIF, Font.CENTER_BASELINE, 14));
    	            defaults.put("Table.font", new Font(Font.SANS_SERIF, Font.PLAIN, 18));
//    	            defaults.put("Table.alternateRowColor", new Color(255,255,255));
//    	            defaults.put("Table.background", new Color(192,192,192));
    	            
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    private JMenuItem aboutMenu_Shortcuts;
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JMenu creditsMenu;
    private javax.swing.JMenuItem creditsMenu_StartingCreditsMenuItem;
    private javax.swing.JPanel duesPanel;
    private javax.swing.JButton duesPanel_AddContactButton;
    private javax.swing.JLabel duesPanel_PersonNameLabel;
    private javax.swing.JTextField duesPanel_PersonNameTextField;
    private javax.swing.JLabel duesPanel_RelatedToLabel;
    private javax.swing.JTextField duesPanel_RelatedToTextField;
    private javax.swing.JScrollPane duesPanel_ScrollPane;
    private javax.swing.JTable duesPanel_Table;
    private DuesPanel_TableModel duesPanel_TableModel;
    private javax.swing.JLabel duesPanel_ValueLabel;
    private javax.swing.JTextField duesPanel_ValueTextField;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem editMenu_MoveDown;
    private javax.swing.JMenuItem editMenu_MoveUp;
    private javax.swing.JMenuItem editMenu_RemoveRow;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fileMenu_ExitMenuItem;
    private javax.swing.JMenuItem fileMenu_OpenMenuItem;
    private javax.swing.JMenuItem fileMenu_StartingNewOperationsMenuItem;
    private javax.swing.JPopupMenu.Separator fileMenu_Separator;
    private HandlingOperationsFileName handlingOperationsFileName;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel operationsPanel;
    private javax.swing.JCheckBox operationsPanel_AccomplisedCheckBox;
    private javax.swing.JButton operationsPanel_AddOperationButton;
    private javax.swing.JLabel operationsPanel_OperationLabel;
    private javax.swing.JTextField operationsPanel_OperationTextField;
    private javax.swing.JScrollPane operationsPanel_ScrollPane;
    private javax.swing.JTable operationsPanel_Table;
    private Operations_TableModel operations_TableModel;
    private javax.swing.JLabel operationsPanel_ValueLabel;
    private javax.swing.JTextField operationsPanel_ValueTextField;
    private OptimizeTables optimizeTables;
    private javax.swing.JPanel saveContactsPanel;
    private javax.swing.JButton saveContactsPanel_AddContactButton;
    private javax.swing.JLabel saveContactsPanel_PersonNameLabel;
    private javax.swing.JTextField saveContactsPanel_PersonNameTextField;
    private javax.swing.JLabel saveContactsPanel_PersonNumberLabel;
    private javax.swing.JTextField saveContactsPanel_PersonNumberTextField;
    private javax.swing.JScrollPane saveContactsPanel_ScrollPane;
    private javax.swing.JTable saveContactsPanel_Table;
    private SaveContactsPanel_TableModel saveContactsPanel_TableModel;
    private StartingAndEndingCreditsHandeler startingAndEndingCreditsHandeler;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JLabel toolBar_BeginningWithLabel;
    private javax.swing.JTextField toolBar_BeginningWithLabelTextField;
    private javax.swing.JLabel toolBar_CreditsTransferedLabel;
    private javax.swing.JTextField toolBar_CreditsTransferedLabelTextField;
    private javax.swing.JLabel toolBar_CreditsYouHaveLabel;
    private javax.swing.JTextField toolBar_CreditsYouHaveLabelTextField;
    private javax.swing.JLabel toolBar_DuesValuesLabel;
    private javax.swing.JTextField toolBar_DuesValuesTextField;
    private ToolBar_DuesValuesJTextFieldHandling toolBar_DuesValuesJTextFieldHandling;
    private ToolBar_OperationsValueTextFieldHandling toolBar_OperationsValueTextFieldHandling;
    private javax.swing.JToolBar.Separator toolBar_Separator1;
    private javax.swing.JToolBar.Separator toolBar_Separator2;
    private javax.swing.JToolBar.Separator toolBar_Separator3;
}
